let dogs =[
    {
        "image_link": "https://api-ninjas.com/images/dogs/affenpinscher.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 2,
        "good_with_strangers": 5,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 11.5,
        "max_height_female": 11.5,
        "max_weight_male": 10.0,
        "max_weight_female": 10.0,
        "min_height_male": 9.0,
        "min_height_female": 9.0,
        "min_weight_male": 7.0,
        "min_weight_female": 7.0,
        "name": "Affenpinscher"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/afghan_hound.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "grooming": 4,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 1,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 18.0,
        "max_height_male": 27.0,
        "max_height_female": 27.0,
        "max_weight_male": 60.0,
        "max_weight_female": 60.0,
        "min_height_male": 25.0,
        "min_height_female": 25.0,
        "min_weight_male": 50.0,
        "min_weight_female": 50.0,
        "name": "Afghan Hound"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/airedale_terrier.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 2,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 5,
        "trainability": 3,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 11.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 23.0,
        "max_height_female": 23.0,
        "max_weight_male": 70.0,
        "max_weight_female": 70.0,
        "min_height_male": 23.0,
        "min_height_female": 23.0,
        "min_weight_male": 50.0,
        "min_weight_female": 50.0,
        "name": "Airedale Terrier"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/akita.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 1,
        "shedding": 3,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 2,
        "playfulness": 3,
        "protectiveness": 5,
        "trainability": 3,
        "energy": 4,
        "barking": 2,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 28.0,
        "max_height_female": 28.0,
        "max_weight_male": 130.0,
        "max_weight_female": 100.0,
        "min_height_male": 26.0,
        "min_height_female": 26.0,
        "min_weight_male": 100.0,
        "min_weight_female": 70.0,
        "name": "Akita"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/alaskan_klee_kai.jpg",
        "shedding": 3,
        "grooming": 2,
        "coat_length": 1,
        "trainability": 3,
        "energy": 4,
        "min_life_expectancy": 13.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 28.0,
        "max_height_female": 28.0,
        "max_weight_male": 130.0,
        "max_weight_female": 100.0,
        "min_height_male": 26.0,
        "min_height_female": 26.0,
        "min_weight_male": 100.0,
        "min_weight_female": 70.0,
        "good_with_children": 0,
        "good_with_other_dogs": 0,
        "drooling": 0,
        "good_with_strangers": 0,
        "playfulness": 0,
        "protectiveness": 0,
        "barking": 0,
        "name": "Alaskan Klee Kai"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/alaskan_malamute.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 5,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 25.0,
        "max_height_female": 25.0,
        "max_weight_male": 85.0,
        "max_weight_female": 75.0,
        "min_height_male": 25.0,
        "min_height_female": 25.0,
        "min_weight_male": 85.0,
        "min_weight_female": 75.0,
        "name": "Alaskan Malamute"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_bulldog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 2,
        "coat_length": 1,
        "trainability": 4,
        "barking": 1,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 12.0,
        "max_height_male": 28.0,
        "max_height_female": 24.0,
        "max_weight_male": 100.0,
        "max_weight_female": 80.0,
        "min_height_male": 20.0,
        "min_height_female": 20.0,
        "min_weight_male": 75.0,
        "min_weight_female": 60.0,
        "grooming": 0,
        "drooling": 0,
        "good_with_strangers": 0,
        "playfulness": 0,
        "protectiveness": 0,
        "energy": 0,
        "name": "American Bulldog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_english_coonhound.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 5,
        "shedding": 2,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 4,
        "barking": 4,
        "min_life_expectancy": 11.0,
        "max_life_expectancy": 12.0,
        "max_height_male": 26.0,
        "max_height_female": 26.0,
        "max_weight_male": 65.0,
        "max_weight_female": 65.0,
        "min_height_male": 24.0,
        "min_height_female": 24.0,
        "min_weight_male": 45.0,
        "min_weight_female": 45.0,
        "name": "American English Coonhound"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_eskimo_dog.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 5,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 4,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 13.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 26.0,
        "max_height_female": 26.0,
        "max_weight_male": 65.0,
        "max_weight_female": 65.0,
        "min_height_male": 24.0,
        "min_height_female": 24.0,
        "min_weight_male": 45.0,
        "min_weight_female": 45.0,
        "name": "American Eskimo Dog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_foxhound.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 3,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 4,
        "barking": 5,
        "min_life_expectancy": 11.0,
        "max_life_expectancy": 13.0,
        "max_height_male": 25.0,
        "max_height_female": 25.0,
        "max_weight_male": 70.0,
        "max_weight_female": 65.0,
        "min_height_male": 22.0,
        "min_height_female": 22.0,
        "min_weight_male": 65.0,
        "min_weight_female": 60.0,
        "name": "American Foxhound"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_hairless_terrier.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 5,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 14.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 16.0,
        "max_height_female": 16.0,
        "max_weight_male": 16.0,
        "max_weight_female": 16.0,
        "min_height_male": 12.0,
        "min_height_female": 12.0,
        "min_weight_male": 12.0,
        "min_weight_female": 12.0,
        "name": "American Hairless Terrier"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_leopard_hound.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 27.0,
        "max_height_female": 27.0,
        "max_weight_male": 70.0,
        "max_weight_female": 70.0,
        "min_height_male": 21.0,
        "min_height_female": 21.0,
        "min_weight_male": 45.0,
        "min_weight_female": 45.0,
        "name": "American Leopard Hound"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_staffordshire_terrier.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 2,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 4,
        "playfulness": 3,
        "protectiveness": 5,
        "trainability": 3,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 19.0,
        "max_height_female": 19.0,
        "max_weight_male": 70.0,
        "max_weight_female": 55.0,
        "min_height_male": 18.0,
        "min_height_female": 18.0,
        "min_weight_male": 55.0,
        "min_weight_female": 40.0,
        "name": "American Staffordshire Terrier"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_water_spaniel.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 5,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 18.0,
        "max_height_female": 18.0,
        "max_weight_male": 45.0,
        "max_weight_female": 40.0,
        "min_height_male": 15.0,
        "min_height_female": 15.0,
        "min_weight_male": 30.0,
        "min_weight_female": 25.0,
        "name": "American Water Spaniel"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/anatolian_shepherd_dog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 1,
        "playfulness": 3,
        "protectiveness": 5,
        "trainability": 2,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 11.0,
        "max_life_expectancy": 13.0,
        "max_height_male": 29.0,
        "max_height_female": 29.0,
        "max_weight_male": 150.0,
        "max_weight_female": 120.0,
        "min_height_male": 29.0,
        "min_height_female": 29.0,
        "min_weight_male": 110.0,
        "min_weight_female": 80.0,
        "name": "Anatolian Shepherd Dog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/appenzeller_sennenhund.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 3,
        "barking": 4,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 22.0,
        "max_height_female": 22.0,
        "max_weight_male": 70.0,
        "max_weight_female": 70.0,
        "min_height_male": 19.0,
        "min_height_female": 19.0,
        "min_weight_male": 48.0,
        "min_weight_female": 48.0,
        "name": "Appenzeller Sennenhund"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/australian_cattle_dog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 4,
        "energy": 5,
        "barking": 1,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 20.0,
        "max_height_female": 20.0,
        "max_weight_male": 50.0,
        "max_weight_female": 50.0,
        "min_height_male": 18.0,
        "min_height_female": 18.0,
        "min_weight_male": 35.0,
        "min_weight_female": 35.0,
        "name": "Australian Cattle Dog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/australian_kelpie.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 4,
        "energy": 5,
        "barking": 1,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 13.0,
        "max_height_male": 20.0,
        "max_height_female": 20.0,
        "max_weight_male": 50.0,
        "max_weight_female": 50.0,
        "min_height_male": 17.0,
        "min_height_female": 17.0,
        "min_weight_male": 35.0,
        "min_weight_female": 35.0,
        "name": "Australian Kelpie"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/australian_shepherd.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 4,
        "protectiveness": 3,
        "trainability": 5,
        "energy": 5,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 23.0,
        "max_height_female": 23.0,
        "max_weight_male": 65.0,
        "max_weight_female": 55.0,
        "min_height_male": 20.0,
        "min_height_female": 20.0,
        "min_weight_male": 50.0,
        "min_weight_female": 40.0,
        "name": "Australian Shepherd"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/australian_stumpy_tail_cattle_dog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 1,
        "shedding": 3,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 1,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 5,
        "barking": 1,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 20.0,
        "max_height_female": 20.0,
        "max_weight_male": 45.0,
        "max_weight_female": 35.0,
        "min_height_male": 18.0,
        "min_height_female": 18.0,
        "min_weight_male": 38.0,
        "min_weight_female": 32.0,
        "name": "Australian Stumpy Tail Cattle Dog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/american_bulldog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 2,
        "coat_length": 1,
        "trainability": 4,
        "barking": 1,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 12.0,
        "max_height_male": 28.0,
        "max_height_female": 24.0,
        "max_weight_male": 100.0,
        "max_weight_female": 80.0,
        "min_height_male": 20.0,
        "min_height_female": 20.0,
        "min_weight_male": 75.0,
        "min_weight_female": 60.0,
        "grooming": 0,
        "drooling": 0,
        "good_with_strangers": 0,
        "playfulness": 0,
        "protectiveness": 0,
        "energy": 0,
        "name": "American Bulldog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/barbado_da_terceira.jpg",
        "good_with_children": 4,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "coat_length": 1,
        "trainability": 5,
        "energy": 5,
        "barking": 5,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 22.0,
        "max_height_female": 22.0,
        "max_weight_male": 60.0,
        "max_weight_female": 57.0,
        "min_height_male": 20.5,
        "min_height_female": 20.5,
        "min_weight_male": 55.0,
        "min_weight_female": 46.0,
        "grooming": 0,
        "drooling": 0,
        "good_with_strangers": 0,
        "playfulness": 0,
        "protectiveness": 0,
        "name": "Barbado da Terceira"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/barbet.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 1,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 2,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 4,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 24.5,
        "max_height_female": 24.5,
        "max_weight_male": 65.0,
        "max_weight_female": 65.0,
        "min_height_male": 19.0,
        "min_height_female": 19.0,
        "min_weight_male": 35.0,
        "min_weight_female": 35.0,
        "name": "Barbet"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/basenji.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 2,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 2,
        "energy": 4,
        "barking": 1,
        "min_life_expectancy": 13.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 17.0,
        "max_height_female": 17.0,
        "max_weight_male": 24.0,
        "max_weight_female": 22.0,
        "min_height_male": 17.0,
        "min_height_female": 17.0,
        "min_weight_male": 24.0,
        "min_weight_female": 22.0,
        "name": "Basenji"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/basset_fauve_de_bretagne.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 4,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 4,
        "barking": 4,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 12.0,
        "max_height_male": 15.5,
        "max_height_female": 15.5,
        "max_weight_male": 35.0,
        "max_weight_female": 35.0,
        "min_height_male": 12.5,
        "min_height_female": 12.5,
        "min_weight_male": 27.0,
        "min_weight_female": 27.0,
        "name": "Basset Fauve de Bretagne"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/basset_hound.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 2,
        "grooming": 3,
        "drooling": 4,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 2,
        "barking": 4,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 13.0,
        "max_height_male": 15.0,
        "max_height_female": 14.0,
        "max_weight_male": 65.0,
        "max_weight_female": 65.0,
        "min_height_male": 12.0,
        "min_height_female": 11.0,
        "min_weight_male": 40.0,
        "min_weight_female": 40.0,
        "name": "Basset Hound"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/bavarian_mountain_scent_hound.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 2,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 3,
        "trainability": 4,
        "energy": 4,
        "barking": 2,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 20.5,
        "max_height_female": 20.5,
        "max_weight_male": 66.0,
        "max_weight_female": 66.0,
        "min_height_male": 17.0,
        "min_height_female": 17.0,
        "min_weight_male": 37.0,
        "min_weight_female": 37.0,
        "name": "Bavarian Mountain Scent Hound"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/beagle.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 4,
        "protectiveness": 2,
        "trainability": 3,
        "energy": 4,
        "barking": 4,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 16.0,
        "max_height_female": 15.0,
        "max_weight_male": 20.0,
        "max_weight_female": 30.0,
        "min_height_male": 14.0,
        "min_height_female": 13.0,
        "min_weight_male": 15.0,
        "min_weight_female": 20.0,
        "name": "Beagle"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/bearded_collie.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 3,
        "grooming": 4,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 4,
        "playfulness": 4,
        "protectiveness": 3,
        "trainability": 3,
        "energy": 4,
        "barking": 5,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 22.0,
        "max_height_female": 22.0,
        "max_weight_male": 55.0,
        "max_weight_female": 55.0,
        "min_height_male": 21.0,
        "min_height_female": 21.0,
        "min_weight_male": 45.0,
        "min_weight_female": 45.0,
        "name": "Bearded Collie"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/beauceron.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 4,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 2,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 3,
        "energy": 5,
        "barking": 3,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 12.0,
        "max_height_male": 27.5,
        "max_height_female": 27.5,
        "max_weight_male": 110.0,
        "max_weight_female": 110.0,
        "min_height_male": 25.5,
        "min_height_female": 25.5,
        "min_weight_male": 70.0,
        "min_weight_female": 70.0,
        "name": "Beauceron"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/bedlington_terrier.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 3,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 11.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 17.5,
        "max_height_female": 17.5,
        "max_weight_male": 23.0,
        "max_weight_female": 23.0,
        "min_height_male": 15.0,
        "min_height_female": 15.0,
        "min_weight_male": 17.0,
        "min_weight_female": 17.0,
        "name": "Bedlington Terrier"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/belgian_laekenois.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 5,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 10.0,
        "max_life_expectancy": 12.0,
        "max_height_male": 26.0,
        "max_height_female": 26.0,
        "max_weight_male": 65.0,
        "max_weight_female": 65.0,
        "min_height_male": 24.0,
        "min_height_female": 24.0,
        "min_weight_male": 55.0,
        "min_weight_female": 55.0,
        "name": "Belgian Laekenois"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/belgian_malinois.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 5,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 14.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 26.0,
        "max_height_female": 26.0,
        "max_weight_male": 80.0,
        "max_weight_female": 60.0,
        "min_height_male": 24.0,
        "min_height_female": 24.0,
        "min_weight_male": 60.0,
        "min_weight_female": 40.0,
        "name": "Belgian Malinois"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/belgian_sheepdog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 5,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 26.0,
        "max_height_female": 26.0,
        "max_weight_male": 75.0,
        "max_weight_female": 60.0,
        "min_height_male": 24.0,
        "min_height_female": 24.0,
        "min_weight_male": 55.0,
        "min_weight_female": 45.0,
        "name": "Belgian Sheepdog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/belgian_tervuren.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 2,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 5,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 14.0,
        "max_height_male": 26.0,
        "max_height_female": 26.0,
        "max_weight_male": 75.0,
        "max_weight_female": 60.0,
        "min_height_male": 24.0,
        "min_height_female": 24.0,
        "min_weight_male": 55.0,
        "min_weight_female": 45.0,
        "name": "Belgian Tervuren"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/bergamasco_sheepdog.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 1,
        "grooming": 1,
        "drooling": 2,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 3,
        "energy": 3,
        "barking": 1,
        "min_life_expectancy": 13.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 23.5,
        "max_height_female": 23.5,
        "max_weight_male": 84.0,
        "max_weight_female": 71.0,
        "min_height_male": 23.5,
        "min_height_female": 23.5,
        "min_weight_male": 70.0,
        "min_weight_female": 57.0,
        "name": "Bergamasco Sheepdog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/berger_picard.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 3,
        "shedding": 3,
        "grooming": 1,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 3,
        "protectiveness": 4,
        "trainability": 4,
        "energy": 4,
        "barking": 2,
        "min_life_expectancy": 12.0,
        "max_life_expectancy": 13.0,
        "max_height_male": 25.5,
        "max_height_female": 25.5,
        "max_weight_male": 70.0,
        "max_weight_female": 70.0,
        "min_height_male": 23.5,
        "min_height_female": 23.5,
        "min_weight_male": 50.0,
        "min_weight_female": 50.0,
        "name": "Berger Picard"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/bernese_mountain_dog.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 5,
        "grooming": 3,
        "drooling": 3,
        "coat_length": 1,
        "good_with_strangers": 4,
        "playfulness": 4,
        "protectiveness": 3,
        "trainability": 4,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 7.0,
        "max_life_expectancy": 10.0,
        "max_height_male": 27.5,
        "max_height_female": 27.5,
        "max_weight_male": 115.0,
        "max_weight_female": 95.0,
        "min_height_male": 25.0,
        "min_height_female": 25.0,
        "min_weight_male": 80.0,
        "min_weight_female": 70.0,
        "name": "Bernese Mountain Dog"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/bichon_frise.jpg",
        "good_with_children": 5,
        "good_with_other_dogs": 5,
        "shedding": 1,
        "grooming": 5,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 5,
        "playfulness": 4,
        "protectiveness": 2,
        "trainability": 4,
        "energy": 4,
        "barking": 3,
        "min_life_expectancy": 14.0,
        "max_life_expectancy": 15.0,
        "max_height_male": 11.5,
        "max_height_female": 11.5,
        "max_weight_male": 18.0,
        "max_weight_female": 18.0,
        "min_height_male": 9.5,
        "min_height_female": 9.5,
        "min_weight_male": 12.0,
        "min_weight_female": 12.0,
        "name": "Bichon Frise"
    },
    {
        "image_link": "https://api-ninjas.com/images/dogs/biewer_terrier.jpg",
        "good_with_children": 3,
        "good_with_other_dogs": 5,
        "shedding": 1,
        "grooming": 3,
        "drooling": 1,
        "coat_length": 1,
        "good_with_strangers": 3,
        "playfulness": 4,
        "protectiveness": 2,
        "trainability": 3,
        "energy": 3,
        "barking": 3,
        "min_life_expectancy": 16.0,
        "max_life_expectancy": 16.0,
        "max_height_male": 11.0,
        "max_height_female": 11.0,
        "max_weight_male": 8.0,
        "max_weight_female": 8.0,
        "min_height_male": 7.0,
        "min_height_female": 7.0,
        "min_weight_male": 4.0,
        "min_weight_female": 4.0,
        "name": "Biewer Terrier"
    }
];

//console.log(dogs.length);
/*for(dog of dogs) {
    console.log(dog["name"]);
}*/